general:
  debug: false
  instance_name: "SearXNG"
  enable_metrics: false

brand: {}

search:
  safe_search: 0
  autocomplete: "bing"
  default_lang: "auto"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

server:
  port: 8899
  bind_address: "127.0.0.1"
  limiter: false
  public_instance: false
  secret_key: "a41df1bd61c99b34b4475562ae413180982d199a22cc2c81ab68fbebc2c25d74"
  base_url: "https://nikfce.xin/search"
  image_proxy: false
  http_protocol_version: "1.0"
  method: "GET"

valkey:
  url: false

ui:
  default_theme: simple
  default_locale: ""
  theme_args:
    simple_style: auto

outgoing:
  request_timeout: 10.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

categories_as_tabs:
  general:
  images:
  news:
  it:

engines:
  # Bing
  - name: bing
    engine: bing
    shortcut: bi

  - name: bing images
    engine: bing_images
    shortcut: bii

  - name: bing news
    engine: bing_news
    shortcut: bin

# to sync with .dockerignore & pyrightconfig.json

*.pyc
*/*.pyc
*~
*.swp
geckodriver.log

.coverage
coverage/

.govm/
.nvm/
cache/
build/
dist/
local/
gh-pages/
*.egg-info/

/package-lock.json
/node_modules/

.idea/

searx/version_frozen.py
.dir-locals.el

.python-version
".gitignore" 29L, 274C                                                                                        1,1          全部
# to sync with .dockerignore & pyrightconfig.json

*.pyc
  - name: bing videos
    engine: bing_videos
    shortcut: biv

  # Baidu
  - name: baidu
    baidu_category: general
    categories: [general]
    engine: baidu
    shortcut: bd

  - name: baidu images
    baidu_category: images
    categories: [images]
    engine: baidu
    shortcut: bdi

  - name: baidu kaifa
    baidu_category: it
    categories: [it]
    engine: baidu
    shortcut: bdk

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'
